### PR TITLE
Use file handles in file-systems

### LINKED ISSUE #514: Fix code scanning alert: Potential file system race condition
# Potential Bug

Fix a potential file system race condition present in [`src/file-systems/base.ts:90`](https://github.com/ericcornelissen/svgo-action/blob/dfc1d73fa838df00c27536cf6d71c9a4c906f1bc/src/file-systems/base.ts#L90) (and potentially other locations, this should be checked for when addressing this issue).

At the time of writing there's no reason to believe this bug has any security implications (despite  this sometimes being the case for this kind of bug) because of the execution environment of this project. Nevertheless, the problem should be fixed.

---

## Problem description

Often it is necessary to check the state of a file before using it. These checks usually take a file name to be checked, and if the check returns positively, then the file is opened or otherwise operated upon.

However, in the time between the check and the operation, the underlying file referenced by the file name could be changed by an attacker, causing unexpected behavior.
Recommendation

Use file descriptors instead of file names whenever possible.

### Example

The following example shows a case where the code checks whether a file inside the `/tmp/` folder exists, and if it doesn't, the file is written to that location.

```javascript
const fs = require("fs");
const os = require("os");
const path = require("path");

const filePath = path.join(os.tmpdir(), "my-temp-file.txt");

if (!fs.existsSync(filePath)) {
  fs.writeFileSync(filePath, "Hello", { mode: 0o600 });
}
```

However, in a multi-user environment the file might be created by another user between the existence check and the write.

This can be avoided by using `fs.open` to get a file descriptor, and then use that file descriptor in the write operation.

```javascript
const fs = require("fs");
const os = require("os");
const path = require("path");

const filePath = path.join(os.tmpdir(), "my-temp-file.txt");

try {
  const fd = fs.openSync(filePath, fs.O_CREAT | fs.O_EXCL | fs.O_RDWR, 0o600);

  fs.writeFileSync(fd, "Hello");
} catch (e) {
  // file existed
}
```

### References

- Wikipedia: [Time-of-check to time-of-use](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use).
- NodeJS: [The FS module](https://nodejs.org/api/fs.html).

### PR DESCRIPTION
**Pull request by ericcornelissen**
### Checklist

- [x] I left no linting errors in my changes.
- [x] I tested my changes.
- [n/a] I updated the documentation according to my changes.
- [x] I added my change to the Changelog.

### Description

Closes #514

### CODE REVIEW

File: src/file-systems/base.ts [hunk 1]
```diff
@@ -18,8 +18,9 @@ interface Params {
     lstatSync(path: string): {
       isFile(): boolean;
     };
+    openSync(path: string, flags: string): number;
```
Comment (ericcornelissen) [inline src/file-systems/base.ts:21]: Replace `flags: string` by only the allowed flags, so far:

```suggestion
    openSync(path: string, flags: "r"): number;
```
